name: Auto Start Falix Server

on:
  schedule:
    - cron: "0,40 * * * *"   # every 40 minutes
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "false"

      - name: Run starter
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: node src/start-falix.js
